cache:
  directories:
    - $HOME/.m2

dist: trusty

language: java

git:
  depth: false

before_script:
  - ./travis-set-branch.sh

script:
  - ./mvnw clean install

install: /bin/true

jdk:
  - oraclejdk8
  - openjdk8

branches:
    except:
        - gh-pages

after_success:
  - ./mvnw -Pcoverage clean integration-test jacoco:report coveralls:report

notifications:
  email:
    - matthieu@brouillard.fr
